language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .
  - pip install -r test-requirements.txt

script:
  # Turning off prospector autodetect because, otherwise, it thinks Django is a dependency and fails.
  - prospector --ignore-patterns='^(?!colander_tools)' --no-autodetect
  - py.test colander_tools
