language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .
  - pip install -r test-requirements.txt

script:
  - prospector --ignore-patterns='^(?!colander_tools)'
  - py.test colander_tools
